[build]
  base = "."
  functions = "./functions"
  publish = "public"
  command = "gatsby build"
[build.environment]
  NODE_VERSION = "12.13.0"
  YARN_VERSION = "1.19.1"
  YARN_FLAGS = "--no-ignore-optional"
