---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Blog post
  create: all
  match: "**/*"
  new_doc_ext: mdx
  templates:
  - blog-post
upload_dir: content/images
public_path: "/images"
front_matter_path: "../images"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: https://github.com/nodejs/docker-node/blob/e886c2c1d3a109ccfe169419f3b30f9794bacf61/16/alpine3.11/Dockerfile
  mount_path: "/"
  working_dir: "/srv"
  instant_preview_command: gatsby develop
