---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://webhook.gatsbyjs.com/hooks/data_source/publish/7023193a-dbe0-4ecf-9c8d-e3e57c361589
sections:
- type: directory
  path: content
  label: Blog posts
  create: all
  match: "**/*"
  new_doc_ext: mdx
  templates:
  - blog-post
upload_dir: content/images
public_path: "../images"
front_matter_path: "../images"
use_front_matter_path: true
file_template: ":day:month:year:filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: https://hub.docker.com/_/node?tab=description&page=1&ordering=last_updated
  mount_path: "/"
  working_dir: "/srv"
  instant_preview_command: gatsby develop
